require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'ClaraWearables' do
  project 'ClaraWearables.xcodeproj'
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # Embed MWDATCore & MWDATCamera dynamic frameworks into the app bundle.
    # CocoaPods doesn't embed vendored dynamic xcframeworks from static pods,
    # so we add a custom build phase to copy and codesign them.
    app_project = installer.aggregate_targets
      .find { |t| t.label == 'Pods-ClaraWearables' }
      &.user_project
    if app_project
      app_target = app_project.targets.find { |t| t.name == 'ClaraWearables' }
      if app_target
        phase_name = 'Embed MWDAT Frameworks'
        unless app_target.shell_script_build_phases.any? { |p| p.name == phase_name }
          phase = app_target.new_shell_script_build_phase(phase_name)
          phase.shell_script = <<~SCRIPT
            MWDAT_DIR="${PODS_ROOT}/../../modules/expo-wearables-camera/ios/Frameworks"
            if [ "${PLATFORM_NAME}" == "iphonesimulator" ]; then
              SLICE="ios-arm64_x86_64-simulator"
            else
              SLICE="ios-arm64"
            fi
            DEST="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
            mkdir -p "${DEST}"
            rsync -av --delete "${MWDAT_DIR}/MWDATCore.xcframework/${SLICE}/MWDATCore.framework" "${DEST}/"
            rsync -av --delete "${MWDAT_DIR}/MWDATCamera.xcframework/${SLICE}/MWDATCamera.framework" "${DEST}/"
            if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" -a "${CODE_SIGNING_REQUIRED:-}" != "NO" -a "${CODE_SIGNING_ALLOWED}" != "NO" ]; then
              /usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements "${DEST}/MWDATCore.framework"
              /usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements "${DEST}/MWDATCamera.framework"
            fi
          SCRIPT
          app_project.save
        end
      end
    end
  end
end
